/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FailedPaymentsRouteImport } from './routes/failed-payments'
import { Route as TransactionIdRouteImport } from './routes/transaction.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FailedPaymentsRoute = FailedPaymentsRouteImport.update({
  id: '/failed-payments',
  path: '/failed-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionIdRoute = TransactionIdRouteImport.update({
  id: '/transaction/$id',
  path: '/transaction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/failed-payments': typeof FailedPaymentsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/failed-payments': typeof FailedPaymentsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/failed-payments': typeof FailedPaymentsRoute
  '/transaction/$id': typeof TransactionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/failed-payments' | '/transaction/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/failed-payments' | '/transaction/$id'
  id: '__root__' | '/' | '/failed-payments' | '/transaction/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FailedPaymentsRoute: typeof FailedPaymentsRoute
  TransactionIdRoute: typeof TransactionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failed-payments': {
      id: '/failed-payments'
      path: '/failed-payments'
      fullPath: '/failed-payments'
      preLoaderRoute: typeof FailedPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction/$id': {
      id: '/transaction/$id'
      path: '/transaction/$id'
      fullPath: '/transaction/$id'
      preLoaderRoute: typeof TransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FailedPaymentsRoute: FailedPaymentsRoute,
  TransactionIdRoute: TransactionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
